config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages
  resources :private_chatrooms

  root to: 'chatrooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy

  scope :public_channels, -> { where(direct_message: false).where(visibility: 'public') }
  scope :direct_messages, -> { where(direct_message: true) }
  scope :private_channels, -> { where(visibility: 'private') }
  scope :private_and_public_channels, -> { where('visibility = ? or visibility = ?', 'public', 'private') }

  def self.direct_chat(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(':')}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      chatroom = new(name: name, direct_message: true)
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end

  def self.private_chat(users, name)
    name = name.to_s

    if chatroom = private_channels.where(name: name).first
      chatroom.users << users
      chatroom
    else
      chatroom = new(name: name, visibility: 'private')
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  scope :recent_messages, -> { order(created_at: :desc).limit(100).reverse }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom
  end

  def destroy
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
    redirect_to chatrooms_path
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.public_channels
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id) if current_user
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit; end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    if params[:chatroom][:visibility] == 'private'
      users = []
      users = params[:user_ids].map { |id| User.find(id) } if params[:user_ids]
      users << current_user
      name = params[:chatroom][:name]
      @chatroom = Chatroom.private_chat(users, name)
    else
      @chatroom = Chatroom.new(chatroom_params)
    end
    respond_to do |format|
      if @chatroom.save && current_user
        @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    if params[:chatroom][:visibility] = 'private'
      users = []
      users = params[:user_ids].map { |id| User.find(id) } if params[:user_ids]
      name = params[:chatroom][:name]
      @chatroom.update(chatroom_params)
      @chatroom = Chatroom.private_chat(users, name)
    else
      @chatroom.update(chatroom_params)
    end
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:id])
  end

  def chatroom_params
    params.require(:chatroom).permit(:name, :visibility)
  end
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController
  before_action :authenticate_user!

  def show
    users = [current_user, User.find(params[:id])]
    @chatroom = Chatroom.direct_chat(users)
    @messages = @chatroom.messages.recent_messages
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
    render 'chatrooms/show'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_chatroom

  def create
    message = @chatroom.messages.new(message_params)
    message.user = current_user
    message.save
    MessageRelayJob.perform_later(message)
  end

  private

  def load_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def message_params
    params.require(:message).permit(:content).merge(user: current_user)
  end
end

app/controllers/private_chatrooms_controller.rb
class PrivateChatroomsController < ApplicationController
  before_action :authenticate_user!

  def new
    @chatroom = Chatroom.new
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name, :visibility)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def channel_name
    Chatroom.find(params[:id]).name
  end

  def channel_users
    Chatroom.find(params[:id]).users.map {|u| p u.email}.join(' , ') 
  end
end

app/views/chatrooms/_add_users.html.erb
<aside class="menu">
  <div class="menu-content">
    <i class="fa fa-unlock-alt"></i><a href="#" id="login">Add users</a>
  </div>
  <div class="arrow-up"></div>
</aside>
<div class="login-form">
  <%= form_for(@chatroom) do |f| %>
  <% if @chatroom.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>
    <ul>
      <% @chatroom.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.select :visibility, [["Public", "public"], ["Private", "private"]], {}, {class: "form-control"} %>
  </div>
  <div class="checkboxes">
    <% (User.all - @chatroom.users | @chatroom.users - User.all).each do |user| %>
    <%= check_box_tag 'user_ids[]', user.id %>
    <%= user.email %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>
</section>

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>
      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Join", chatroom_chatroom_users_path(chatroom), method: :post %></td>
        <td><%= link_to "Leave", chatroom_chatroom_users_path(chatroom), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/show.html.erb
<% content_for :title, "#{channel_name}| Kabel" %>
<div class="header">
  <div class="top"></div>
  <div class="channel-menu">
    <span class="channel-menu_name"><span class="channel-menu_prefix">#</span> <%= channel_name %></span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="new_private_chatroom"><%= link_to 'New Private Chatroom', new_private_chatroom_path %></div>
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <% if user_signed_in? %>
      <ul>
        <% current_user.chatrooms.private_and_public_channels.each do |chatroom| %>
        <% if chatroom.id.to_s == params[:id].to_s %>
        <li class="channel active">
          <%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %>
        </li>
        <% else %>
        <li><%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></li>
        <% end %>
        <%= @users_ids %>
        <% end %>
      </ul>
      <br>
      <h2 class="listings_header">Users</h2>
      <ul>
        <% (User.all - [current_user]).each do |user| %>
        <% if user.id.to_s == params[:id].to_s %>
        <li class="channel active">
          <%= link_to user.email, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_chat([current_user, user]).id } %>
        </li>
        <% else %>
        <li><%= link_to user.email, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_chat([current_user, user]).id } %></li>
        <% end %>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
  <div class="message-history" id="messages" data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>'>
    <%= render 'add_users' %>
    <%= channel_users %>
    <%= render @messages %>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic"></span><span class="user-menu_username"><%= current_user.email %></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
  </div>
  <div class="input-box">
    <%= form_for [@chatroom, Message.new] do |f| %>
    <%= f.text_area :content, rows: 2, cols: 200, class: "form-control", id: "message_input", autofocus: true %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'Kabel' %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,900" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript"></script>
  </head>
  <body>

    <%= yield %>

    <script type="text/javascript">

	$(document).ready(function () {
		var arrow = $(".arrow-up");
		var form = $(".login-form");
		var status = false;
		$("#login").click(function (event) {
			event.preventDefault();
			if (status == false) {
				arrow.fadeIn();
				form.fadeIn();
				status = true;
			} else {
				arrow.fadeOut();
				form.fadeOut();
				status = false;
			}
		})
	})
    </script>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <a href="" class="message_profile-pic"></a>
  <a href="" class="message_username"><strong><%= message.user.email %></strong></a>
  <span class="message_star"></span>
  <span class="message_content">
    <%= message.content %>
  </span>
</div>

app/views/messages/create.js.erb
$("#new_message")[0].reset()

app/views/private_chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
<% if chatroom.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>
  <ul>
    <% chatroom.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.select :visibility, [["Public", "public"], ["Private", "private"]], {}, {class: "form-control"} %>
</div>
<% (User.all - [current_user]).each do |user| %>
<%= check_box_tag 'user_ids[]', user.id %>
<%= user.email %>
<% end %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/private_chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/rooms/show.html.erb
<% content_for :title, 'general | Kabel' %>
<div class="header">
  <div class="team-menu">Kabel</div>

  <div class="channel-menu">
    <span class="channel-menu_name"><span class="channel-menu_prefix">#</span> general</span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <ul class="channel_list">
        <li class="channel active">
          <a class="channel_name"><span><span class="prefix">#</span>general</span></a>
        </li>
      </ul>
    </div>
    <div class="listings_direct-messages">
      <ul class="channel_list">
        <li class="channel">
        </li>
      </ul>
    </div>
  </div>
  <div class="message-history" id="messages">
    <%= render @messages %>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic"></span><span class="user-menu_username"><%= current_user.email %></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
  </div>
  <div class="input-box">
    <input type="text" class="input-box_text" id="message_input"/>
  </div>
</div>